kind: Kustomization
namespace: monitoring
helmCharts:
  - name: kube-prometheus
    releaseName: kube-prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.19.1
    namespace: monitoring
    valuesFile: values.yaml
