kind: Kustomization
namespace: monitoring
helmCharts:
  - name: prometheus
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.21.0
    namespace: monitoring
    valuesFile: values.yaml
