operator:
  enabled: true

prometheus:
  enabled: true
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 8Gi
  serviceMonitor:
    enabled: true
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: "istiod"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istiod;http-monitoring
        - job_name: "istio-mesh"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-telemetry;prometheus

        # Scrape config for envoy stats
        - job_name: "envoy-stats"
          metrics_path: /stats/prometheus
          kubernetes_sd_configs:
            - role: pod

          scrape_interval: 15s
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: ".*-envoy-prom"
            - source_labels:
                [
                  __address__,
                  __meta_kubernetes_pod_annotation_prometheus_io_port,
                ]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:15090
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod_name

        - job_name: "istio-policy"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-policy;http-monitoring

        - job_name: "istio-telemetry"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-telemetry;http-monitoring

        - job_name: "pilot"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-pilot;http-monitoring

        - job_name: "galley"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-galley;http-monitoring

        - job_name: "citadel"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system

          scrape_interval: 15s
          relabel_configs:
            - source_labels:
                [
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
                ]
              action: keep
              regex: istio-citadel;http-monitoring
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/load-balancer-name: system-alb
      alb.ingress.kubernetes.io/group.name: "system-alb-group"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:221370546661:certificate/6f73fffc-dc0f-4c85-a295-147c64be7fcb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
    path: /
    pathType: Prefix
    backend:
      service:
        name: kube-prometheus-prometheus
        port:
          number: 80
    hostname: prometheus.smartseo.kr

alertmanager:
  enabled: false

blackboxExporter:
  enabled: false

coreDns:
  enabled: false

kubeProxy:
  enabled: false
